#!/bin/bash
gcc domSet.c -o dom

# check if results file exists
if [ -f results ]; then
    echo -n "" > results
fi

# run every file in the folder
for i in files/*; do
    ./dom < $i >> results
done

# sorts & counts the results using gawk
gawk '
     { 
          count[$1]++ 
     }
     END { 
          n = asorti(count, sorted)
          for (i = 1; i <= n; i++) {
               printf "%i %i\n", sorted[i], count[sorted[i]] > "summary"
          }
     } ' results

# generate graph of results using gnu plot
gnuplot domSet.gnuplot
