#!/bin/bash
gcc domSet.c -o domSet

# check if results file exists
if [ -f results ]; then
    echo -n "" > results
fi

# current file number
fileNum=0

# max number of files
LIMIT=9

# location where files should be located
pwd=$(pwd)

# start looping through all possible eos machines
for i in {1..32}; do

    # machine to run files
    machine="eos$(printf '%02d' $i)"

    # searchs the known hosts file for eos current machine
    is_known=$(ssh-keygen -l -f ~/.ssh/known_hosts -F $machine)

    # check if the machine is valid
    if [ ! -z "$is_known" ]; then

        # generate the file path
        filePath="files/file$((fileNum++))*"

        # generate the command to run on the remote machine
        ssh $machine 'cd '$pwd'; for i in '$filePath'; do ./domSet < $i >> results; done'
    fi

    # check if all the files have been run
    if (( $fileNum > 9 )); then

        # stop searching for eos machines to execute program
        break
    fi
done
wait

# sort the results file & redirect the ouput
sort -n results -o sortedResults

# count the number of results for each value
uniq -c sortedResults summary

# generate graph of results using gnu plot
gnuplot domSet.gnuplot
